/*

 MAZEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 19 x 17
   Tile set      : Z:\home\vmware\gbtd22\mazesprize.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MazeMapWidth 19
#define MazeMapHeight 17
#define MazeMapBank 0

extern unsigned char MazeMap[];

/* End of MAZEMAP.H */
