/*

 BACKGROUNDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : Z:\home\vmware\gbtd22\simple_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundmapWidth 40
#define backgroundmapHeight 18
#define backgroundmapBank 0

unsigned char windowmap[] =
{
  0x13,0x10,0x17,0x17,0x1A
};

/* End of BACKGROUNDMAP.C */
