/*

 LOONEYTUNES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define LooneyTunesBank 0

// /* Super Gameboy palette 0 */
// #define LooneyTunesSGBPal0c0 6076
// #define LooneyTunesSGBPal0c1 8935
// #define LooneyTunesSGBPal0c2 6596
// #define LooneyTunesSGBPal0c3 5344

// /* Super Gameboy palette 1 */
// #define LooneyTunesSGBPal1c0 6076
// #define LooneyTunesSGBPal1c1 8935
// #define LooneyTunesSGBPal1c2 6596
// #define LooneyTunesSGBPal1c3 5344

// /* Super Gameboy palette 2 */
// #define LooneyTunesSGBPal2c0 6076
// #define LooneyTunesSGBPal2c1 8935
// #define LooneyTunesSGBPal2c2 6596
// #define LooneyTunesSGBPal2c3 5344

// /* Super Gameboy palette 3 */
// #define LooneyTunesSGBPal3c0 6076
// #define LooneyTunesSGBPal3c1 8935
// #define LooneyTunesSGBPal3c2 6596
// #define LooneyTunesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define LooneyTunesCGBPal0c0 32767
#define LooneyTunesCGBPal0c1 32492
#define LooneyTunesCGBPal0c2 26016
#define LooneyTunesCGBPal0c3 5662

/* Gameboy Color palette 1 */
#define LooneyTunesCGBPal1c0 31639
#define LooneyTunesCGBPal1c1 32767
#define LooneyTunesCGBPal1c2 5182
#define LooneyTunesCGBPal1c3 0

// /* Gameboy Color palette 2 */
// #define LooneyTunesCGBPal2c0 6076
// #define LooneyTunesCGBPal2c1 8935
// #define LooneyTunesCGBPal2c2 6596
// #define LooneyTunesCGBPal2c3 5344

// /* Gameboy Color palette 3 */
// #define LooneyTunesCGBPal3c0 6076
// #define LooneyTunesCGBPal3c1 8935
// #define LooneyTunesCGBPal3c2 6596
// #define LooneyTunesCGBPal3c3 5344

// /* Gameboy Color palette 4 */
// #define LooneyTunesCGBPal4c0 6076
// #define LooneyTunesCGBPal4c1 8935
// #define LooneyTunesCGBPal4c2 6596
// #define LooneyTunesCGBPal4c3 5344

// /* Gameboy Color palette 5 */
// #define LooneyTunesCGBPal5c0 6076
// #define LooneyTunesCGBPal5c1 8935
// #define LooneyTunesCGBPal5c2 6596
// #define LooneyTunesCGBPal5c3 5344

// /* Gameboy Color palette 6 */
// #define LooneyTunesCGBPal6c0 6076
// #define LooneyTunesCGBPal6c1 8935
// #define LooneyTunesCGBPal6c2 6596
// #define LooneyTunesCGBPal6c3 5344

// /* Gameboy Color palette 7 */
// #define LooneyTunesCGBPal7c0 6076
// #define LooneyTunesCGBPal7c1 8935
// #define LooneyTunesCGBPal7c2 6596
// #define LooneyTunesCGBPal7c3 5344


/* CGBpalette entries. */
extern unsigned char LooneyTunesCGB[];
/* Start of tile array. */
extern unsigned char LooneyTunes[];

/* End of LOONEYTUNES.H */
